- name: Start web server
  hosts: nodes
  user: root

  tasks:
    - name: Install GitHub3
      pip:
        name: github3

    - name: Get release
      community.general.github_release:
        user: wiegg
        repo: lnk
        action: latest_release

    - name: Find Standalone
      find:
        paths: .
        recurse: yes
        pattern: "*lnk*"

- name: Setup redis
  hosts: redis
  user: root

  tasks:
    - name: Update
      apt: update_cache=yes

    - name: Install redis
      apt: name=redis-server state=latest

      notify:
        - systemctl restart redis.service

    - name: Restart Redis Server
      service: name=redis state=restarted enabled=yes