- name: Start web server
  hosts: nodes
  user: root

  tasks:
    - name: Create lnk group
      group:
        name: lnk
        state: present

    - name: Create lnk user
      user:
        name: lnk
        groups: ["lnk"]
        shell: /sbin/nologin
        append: yes
        state: present
        create_home: no

    - name: Get Release Info
      uri:
        url: https://api.github.com/repos/wiegg/lnk/releases/latest
        return_content: true
      register: release_response

    - name: Get Asset Info
      uri:
        url: "{{ release_response.json.assets[0].url }}"
        return_content: true
      register: asset_response

    - name: Download binary
      get_url:
        url: "{{ asset_response.json.browser_download_url }}"
        dest: /srv/lnk

    - name: Copy service to systemd
      copy:
        src: services/lnk.service
        dest: /etc/systemd/system
        owner: root
        group: root

    - name: Copy binary to bin
      copy:
        remote_src: true
        src: /srv/lnk
        dest: /usr/local/bin
        mode: 0755
        owner: root
        group: root

    - name: Start lnk
      systemd:
        name: lnk
        state: started
        enabled: yes

- name: Setup redis
  hosts: db
  user: root

  tasks:
    - name: Update
      apt: update_cache=yes

    - name: Install redis
      apt: name=redis-server state=latest

    - name: Copy redis config
      copy:
        src: services/redis.conf
        dest: /etc/redis/redis.conf
        group: redis
        owner: redis

    - name: Restart Redis Server
      service: name=redis state=restarted enabled=yes