name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  preview:
    name: 'Preview changes'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      continue-on-error: true
      run: terraform plan -out iaac.tfplan
      env:
        TF_VAR_token: ${{ secrets.API_KEY_READ }}

    # add plan to pull request
    - name: Update Pull Request
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          ## Suggested changes:

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    # Checks if plan was successful
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    # upload plan as artifact for review
    - uses: actions/upload-artifact@v2
      with:
        name: plan
        path: iaac.tfplan

  deploy:
    name: 'Deploy changes'
    runs-on: ubuntu-latest
    needs: preview
    environment: Hetzner
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Display structure of downloaded files
      run: ls -R . && echo $TOKEN
      env:
        TOKEN: ${{ secrets.API_KEY }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -out iaac.tfplan
      env:
        TF_VAR_token: ${{ secrets.API_KEY }}

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -auto-approve iaac.tfplan